version: '3.3'

services:
  app:
    build: ./node
    container_name: app
    restart: unless-stopped
    networks:
      - node-network
    environment:
      - DB_HOST=db
      - DB_PASSWORD=password
    volumes:
      - ./node:/usr/src/app
    ports:
      - "3000:3000"
    depends_on:
      - db

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - node-network
    ports:
      - 8080:80
    depends_on:
      - app
      - db

  db:
    image: mysql:5.7
    command: --innodb_use_native_aio=0
    platform: linux/x86_64
    container_name: db
    networks:
      - node-network
    environment:
      MYSQL_DATABASE: 'nodedb'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_AUTHENTICATION_PLUGIN: mysql_native_password
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - '3306:3306'
    expose:
      - '3306'

networks:
  node-network:
    driver: bridge
